post_install() {
    systemctl enable --now dynamic-wallpaper.timer

    echo "YOU NEED TO ADD THE FOLLOWING COMMAND TO YOUR HYPRLAND CONFIG"
    ehco "exec-once = swww init"
    echo "OTHERWISE THE WALLPAPER WILL REVERT TO THE DEFAULT ONE"
}

post_upgrade() {
    systemctl enable --now dynamic-wallpaper.timer
}

pre_upgrade() {
    systemctl disable --now dynamic-wallpaper.timer
}

post_remove() {
    systemctl disable --now dynamic-wallpaper.timer
}