#!/bin/sh
set -e
ln -sf /usr/local/bin/daily-wallpaper.py /etc/cron.hourly/daily-wallpaper
if [ -f /usr/local/bin/daily-wallpaper.py ]; then
    /usr/local/bin/daily-wallpaper.py
else
    echo "Error: daily-wallpaper.py not found."
    exit 1
fi
exit 0