name: Build and Upload DEB Package
permissions:
  contents: write

on:
  push:
    branches: [ main ]
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Build DEB package
        run: dpkg-deb --build daily-wallpaper

      - name: Upload DEB artifact
        uses: actions/upload-artifact@v4
        with:
          name: daily-wallpaper.deb
          path: daily-wallpaper.deb

      - name: Create Release
        uses: softprops/action-gh-release@v1
        with:
          tag_name: v1.0.${{ github.run_number }}
          name: Daily Wallpaper v1.0.${{ github.run_number }}
          draft: false
          prerelease: false
        env:
          GITHUB_TOKEN: ${{ secrets.CUSTOM_GITHUB_TOKEN }}

      - name: Upload Release Asset
        uses: softprops/action-gh-release@v1
        with:
          files: daily-wallpaper.deb
        env:
          GITHUB_TOKEN: ${{ secrets.CUSTOM_GITHUB_TOKEN }}