name: Build and Upload Arch Package
permissions:
  contents: write

on:
  push:
    tags:
      - '*'   # Trigger on any tag push

jobs:
  build:
    runs-on: archlinux-latest
    container:
      image: archlinux:latest
      options: --privileged

    steps:
      - name: Install build dependencies
        run: |
          pacman -Syu --noconfirm
          pacman -S --noconfirm base-devel git sudo

      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup non-root user for makepkg
        run: |
          useradd -m builder
          echo "builder ALL=(ALL) NOPASSWD: ALL" >> /etc/sudoers
          chown -R builder:builder .

      - name: Build package
        run: |
          cd daily-wallpaper-arch
          sudo -u builder makepkg -f

      - name: Upload package as artifact
        uses: actions/upload-artifact@v4
        with:
          name: daily-wallpaper-arch
          path: daily-wallpaper-arch/daily-wallpaper-*.pkg.tar.zst

      - name: Create Release
        uses: softprops/action-gh-release@v1
        with:
          tag_name: ${{ github.ref_name }}
          name: Daily Wallpaper ${{ github.ref_name }}
          draft: false
          prerelease: false
          files: daily-wallpaper-arch/daily-wallpaper-*.pkg.tar.zst
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}