name: Build and Upload DEB Package
permissions:
  contents: write

on:
  push:
    tags:
      - '*'   # Trigger on any tag push

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Build DEB package
        run: dpkg-deb --build daily-wallpaper-deb daily-wallpaper.deb

      - name: Upload DEB artifact
        uses: actions/upload-artifact@v4
        with:
          name: daily-wallpaper.deb
          path: daily-wallpaper.deb

      - name: Create Release
        uses: softprops/action-gh-release@v1
        with:
          tag_name: ${{ github.ref_name }}
          name: Daily Wallpaper ${{ github.ref_name }}
          draft: false
          prerelease: false
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Upload Release Asset
        uses: softprops/action-gh-release@v1
        with:
          files: daily-wallpaper.deb
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}